"""add created_at to chat_sessions

Revision ID: ccacc6c696af
Revises: e2f64c5b0a94
Create Date: 2026-06-30 00:05:57.697554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccacc6c696af'
down_revision: Union[str, Sequence[str], None] = 'e2f64c5b0a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'created_at')
    # ### end Alembic commands ###
